<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2015-12-09T23:48:04+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'titlecard',
    'version_installed' => '5.7.5.2',
    'misc' => array(
        'access_entity_updated' => 1427217583,
        'latest_version' => '5.7.5.3',
        'seen_introduction' => true,
        'do_page_reindex_check' => false,
    ),
    'debug' => array(
        'detail' => 'debug',
        'display_errors' => true,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
    ),
);
