<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-01-21T17:10:37+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Titlecard Capital',
    'version_installed' => '5.7.5.2',
    'misc' => array(
        'access_entity_updated' => 1427217583,
        'latest_version' => '5.7.5.4',
        'seen_introduction' => true,
        'do_page_reindex_check' => false,
    ),
    'debug' => array(
        'detail' => 'debug',
        'display_errors' => true,
    ),
    'cache' => array(
        'blocks' => true,
        'assets' => true,
        'theme_css' => true,
        'overrides' => true,
        'pages' => 'blocks',
        'full_page_lifetime' => 'custom',
        'full_page_lifetime_value' => '1',
    ),
    'theme' => array(
        'compress_preprocessor_output' => true,
        'generate_less_sourcemap' => false,
    ),
    'seo' => array(
        'canonical_url' => '',
        'canonical_ssl_url' => '',
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => 1,
    ),
);
